"""Run V4 swing, H1/M30 satellite, and combined portfolio windows.

The combined curve is a normalized-return portfolio approximation generated by
multiplying both engines' independent equity indices. It is suitable for
research screening. The live portfolio additionally prevents opposing exposure,
which this approximation reports but does not perfectly re-simulate.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd

from gbpusd_satellite_backtest import (
    SatelliteConfig,
    backtest as satellite_backtest,
    load_mt5_csv,
)
from gbpusd_v4_backtest import (
    V4Config,
    backtest as v4_backtest,
    load_mt5_h4,
)

WINDOWS = (10, 5, 3, 2)


def utc_timestamp(value) -> pd.Timestamp:
    timestamp = pd.Timestamp(value)
    return timestamp.tz_localize("UTC") if timestamp.tzinfo is None else timestamp.tz_convert("UTC")


def maximum_drawdown_percent(series: pd.Series) -> float:
    if series.empty:
        return 0.0
    peak = series.cummax()
    drawdown = (peak - series) / peak.replace(0, np.nan)
    return float(drawdown.max() * 100)


def normalized_curve(equity: pd.DataFrame, initial_balance: float) -> pd.Series:
    if equity.empty:
        return pd.Series(dtype=float)
    frame = equity.copy()
    frame["time"] = pd.to_datetime(frame["time"], utc=True)
    return frame.drop_duplicates("time").set_index("time")["equity"] / initial_balance


def trade_returns(trades: pd.DataFrame, engine: str) -> pd.DataFrame:
    if trades.empty:
        return pd.DataFrame(columns=["time", "engine", "return_fraction", "pnl"])
    frame = trades.copy()
    frame["time"] = pd.to_datetime(frame["exit_time"], utc=True)
    if "balance_before" not in frame:
        frame["balance_before"] = frame["balance"] - frame["pnl"]
    frame["return_fraction"] = frame["pnl"] / frame["balance_before"].replace(0, np.nan)
    frame["engine"] = engine
    return frame[["time", "engine", "return_fraction", "pnl"]]


def combined_metrics(v4_trades: pd.DataFrame, v4_equity: pd.DataFrame,
                     sat_trades: pd.DataFrame, sat_equity: pd.DataFrame,
                     initial_balance: float) -> tuple[dict, pd.DataFrame, pd.DataFrame]:
    v4_curve = normalized_curve(v4_equity, initial_balance)
    sat_curve = normalized_curve(sat_equity, initial_balance)
    index = v4_curve.index.union(sat_curve.index).sort_values()
    if index.empty:
        return {}, pd.DataFrame(), pd.DataFrame()
    v4_aligned = v4_curve.reindex(index).ffill().fillna(1.0)
    sat_aligned = sat_curve.reindex(index).ffill().fillna(1.0)
    combined = initial_balance * v4_aligned * sat_aligned
    equity = pd.DataFrame({
        "time": index,
        "v4_index": v4_aligned.to_numpy(),
        "satellite_index": sat_aligned.to_numpy(),
        "combined_equity": combined.to_numpy(),
    })

    events = pd.concat([
        trade_returns(v4_trades, "V4_SWING"),
        trade_returns(sat_trades, "SATELLITE_INTRADAY"),
    ], ignore_index=True).sort_values("time")
    balance = initial_balance
    event_rows = []
    for event in events.itertuples(index=False):
        pnl = balance * float(event.return_fraction)
        balance += pnl
        event_rows.append({
            "time": event.time,
            "engine": event.engine,
            "return_fraction": event.return_fraction,
            "portfolio_pnl": pnl,
            "portfolio_balance": balance,
        })
    event_frame = pd.DataFrame(event_rows)
    gains = event_frame.loc[event_frame.portfolio_pnl > 0, "portfolio_pnl"].sum() if not event_frame.empty else 0.0
    losses = -event_frame.loc[event_frame.portfolio_pnl < 0, "portfolio_pnl"].sum() if not event_frame.empty else 0.0
    metrics = {
        "initial_balance": initial_balance,
        "ending_balance": float(combined.iloc[-1]),
        "net_profit": float(combined.iloc[-1] - initial_balance),
        "return_percent": float((combined.iloc[-1] / initial_balance - 1) * 100),
        "trades": int(len(v4_trades) + len(sat_trades)),
        "v4_trades": int(len(v4_trades)),
        "satellite_trades": int(len(sat_trades)),
        "profit_factor": float(gains / losses) if losses else float("inf"),
        "maximum_drawdown_percent": maximum_drawdown_percent(combined),
        "method": "normalized-return portfolio approximation",
    }
    return metrics, equity, event_frame


def overlapping_opposite_count(v4_trades: pd.DataFrame, sat_trades: pd.DataFrame) -> int:
    if v4_trades.empty or sat_trades.empty:
        return 0
    count = 0
    for sat in sat_trades.itertuples():
        active = v4_trades[
            (pd.to_datetime(v4_trades.entry_time, utc=True) <= pd.Timestamp(sat.entry_time))
            & (pd.to_datetime(v4_trades.exit_time, utc=True) >= pd.Timestamp(sat.entry_time))
        ]
        if not active.empty and any(int(side) != int(sat.side) for side in active.side):
            count += 1
    return count


def run_window(name: str, start: pd.Timestamp, end: pd.Timestamp,
               h4: pd.DataFrame, m30: pd.DataFrame, out_dir: Path,
               initial_balance: float, satellite_risk: float) -> dict:
    v4_cfg = V4Config(initial_balance=initial_balance, risk_percent=0.35)
    sat_cfg = SatelliteConfig(initial_balance=initial_balance, risk_percent=satellite_risk)
    v4_trades, v4_equity, v4_metrics = v4_backtest(
        h4, v4_cfg, start=start.isoformat(), end=end.isoformat()
    )
    sat_trades, sat_equity, sat_metrics = satellite_backtest(
        m30, sat_cfg, start=start.isoformat(), end=end.isoformat()
    )
    combined, combined_equity, combined_events = combined_metrics(
        v4_trades, v4_equity, sat_trades, sat_equity, initial_balance
    )
    combined["opposing_overlap_candidates"] = overlapping_opposite_count(v4_trades, sat_trades)
    window_dir = out_dir / name
    window_dir.mkdir(parents=True, exist_ok=True)
    v4_trades.to_csv(window_dir / "v4_trades.csv", index=False)
    sat_trades.to_csv(window_dir / "satellite_trades.csv", index=False)
    combined_equity.to_csv(window_dir / "combined_equity.csv", index=False)
    combined_events.to_csv(window_dir / "combined_events.csv", index=False)
    payload = {
        "window": name, "start": start.isoformat(), "end": end.isoformat(),
        "v4": v4_metrics, "satellite": sat_metrics, "combined": combined,
    }
    (window_dir / "metrics.json").write_text(
        json.dumps(payload, indent=2, default=str) + "\n", encoding="utf-8"
    )
    return payload


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--h4", type=Path, required=True)
    parser.add_argument("--m30", type=Path, required=True)
    parser.add_argument("--out-dir", type=Path, default=Path("research/portfolio_results"))
    parser.add_argument("--initial-balance", type=float, default=5000.0)
    parser.add_argument("--satellite-risk", type=float, default=0.12)
    parser.add_argument(
        "--allow-partial-coverage", action="store_true",
        help="Run the maximum available M30 window when requested windows are unavailable.",
    )
    args = parser.parse_args()

    h4 = load_mt5_h4(args.h4)
    m30 = load_mt5_csv(args.m30)
    latest = min(
        utc_timestamp(h4.time.max()) + pd.Timedelta(hours=4),
        utc_timestamp(m30.time.max()) + pd.Timedelta(minutes=30),
    )
    earliest_m30 = utc_timestamp(m30.time.min())
    args.out_dir.mkdir(parents=True, exist_ok=True)
    summary = []
    for years in WINDOWS:
        requested_start = latest - pd.DateOffset(years=years)
        if earliest_m30 > requested_start:
            summary.append({
                "window": f"{years}y",
                "status": "INSUFFICIENT_M30_HISTORY",
                "requested_start": requested_start.isoformat(),
                "available_start": earliest_m30.isoformat(),
                "available_end": latest.isoformat(),
            })
            continue
        result = run_window(
            f"{years}y", requested_start, latest, h4, m30, args.out_dir,
            args.initial_balance, args.satellite_risk,
        )
        result["status"] = "COMPLETED"
        summary.append(result)

    if args.allow_partial_coverage and not any(item.get("status") == "COMPLETED" for item in summary):
        result = run_window(
            "available", earliest_m30, latest, h4, m30, args.out_dir,
            args.initial_balance, args.satellite_risk,
        )
        result["status"] = "COMPLETED_PARTIAL_COVERAGE"
        summary.append(result)

    (args.out_dir / "summary.json").write_text(
        json.dumps(summary, indent=2, default=str) + "\n", encoding="utf-8"
    )
    print(json.dumps(summary, indent=2, default=str))


if __name__ == "__main__":
    main()
