"""Trade-level synchronized replay and verification for Strategy Engine V8.

The input is the accepted synchronized-trade ledger generated by the historical
engine simulations. Each row already contains the exact reserved risk and R
outcome. This module independently rebuilds realized and full-open-risk stress
equity, then reports portfolio and per-engine metrics.

It is not an OHLC/tick simulator. Its purpose is to verify portfolio
coordination after the individual engines have produced their trade ledgers.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import pandas as pd

from .strategy_engine_v8 import DEFAULT_RULES

_REQUIRED_COLUMNS = {
    "symbol",
    "engine",
    "setup",
    "side",
    "entry_time",
    "exit_time",
    "risk_percent",
    "risk_dollars",
    "r_multiple",
    "pnl",
}


@dataclass(frozen=True)
class Performance:
    trades: int
    net_profit: float
    return_percent: float
    profit_factor: float
    win_rate: float
    average_trade: float
    maximum_win: float
    maximum_loss: float
    maximum_drawdown_percent: float


@dataclass(frozen=True)
class ReplayResult:
    initial_balance: float
    ending_balance: float
    realized_drawdown_percent: float
    open_risk_stress_drawdown_percent: float
    portfolio: Performance
    engine_summary: list[dict[str, Any]]
    rejected_candidates: int
    rejection_reasons: dict[str, int]
    methodology: str

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def load_synchronized_trades(path: str | Path) -> pd.DataFrame:
    frame = pd.read_csv(path)
    missing = _REQUIRED_COLUMNS - set(frame.columns)
    if missing:
        raise ValueError(f"Trade ledger is missing required columns: {sorted(missing)}")

    frame = frame.copy()
    frame["entry_time"] = pd.to_datetime(frame["entry_time"], utc=True, errors="raise")
    frame["exit_time"] = pd.to_datetime(frame["exit_time"], utc=True, errors="raise")
    for column in ("risk_percent", "risk_dollars", "r_multiple", "pnl"):
        frame[column] = pd.to_numeric(frame[column], errors="raise")

    if (frame["exit_time"] < frame["entry_time"]).any():
        raise ValueError("Trade ledger contains an exit before its entry")
    if (frame["risk_percent"] <= 0).any() or (frame["risk_dollars"] <= 0).any():
        raise ValueError("Risk values must be positive")
    return frame.reset_index(drop=True)


def _maximum_drawdown_percent(values: list[float]) -> float:
    if not values:
        return 0.0
    peak = values[0]
    maximum = 0.0
    for value in values:
        peak = max(peak, value)
        if peak > 0:
            maximum = max(maximum, (peak - value) / peak * 100.0)
    return maximum


def _profit_factor(pnl: pd.Series) -> float:
    gross_profit = float(pnl[pnl > 0].sum())
    gross_loss = float(-pnl[pnl < 0].sum())
    if gross_loss == 0:
        return float("inf") if gross_profit > 0 else 0.0
    return gross_profit / gross_loss


def _performance(
    frame: pd.DataFrame,
    initial_balance: float,
    drawdown_percent: float,
) -> Performance:
    pnl = frame["pnl"]
    net = float(pnl.sum())
    return Performance(
        trades=int(len(frame)),
        net_profit=net,
        return_percent=(net / initial_balance * 100.0) if initial_balance else 0.0,
        profit_factor=_profit_factor(pnl),
        win_rate=float((pnl > 0).mean()) if len(frame) else 0.0,
        average_trade=float(pnl.mean()) if len(frame) else 0.0,
        maximum_win=float(pnl.max()) if len(frame) else 0.0,
        maximum_loss=float(pnl.min()) if len(frame) else 0.0,
        maximum_drawdown_percent=drawdown_percent,
    )


def build_equity_curves(
    frame: pd.DataFrame,
    initial_balance: float = DEFAULT_RULES.initial_balance,
) -> tuple[list[float], list[float]]:
    """Return realized and worst-case open-risk equity at every event."""

    rows = frame.reset_index(drop=True)
    events: list[tuple[pd.Timestamp, int, int, str]] = []
    for row_id, row in rows.iterrows():
        entry_time = row["entry_time"]
        exit_time = row["exit_time"]
        events.append((entry_time, 1, row_id, "entry"))
        # Existing exits happen before new entries. A zero-duration position must
        # still be entered before its own exit at the same timestamp.
        exit_priority = 2 if exit_time == entry_time else 0
        events.append((exit_time, exit_priority, row_id, "exit"))
    events.sort(key=lambda event: (event[0], event[1], event[2]))

    balance = float(initial_balance)
    open_risk: dict[int, float] = {}
    realized = [balance]
    stress = [balance]

    for _time, _priority, row_id, event_type in events:
        row = rows.iloc[row_id]
        if event_type == "entry":
            open_risk[row_id] = float(row["risk_dollars"])
        else:
            if row_id not in open_risk:
                raise ValueError(f"Exit event for trade {row_id} was not open")
            open_risk.pop(row_id)
            balance += float(row["pnl"])

        realized.append(balance)
        stress.append(balance - sum(open_risk.values()))

    if open_risk:
        raise ValueError("Replay ended with open positions")
    return realized, stress


def load_rejections(path: str | Path | None) -> tuple[int, dict[str, int]]:
    if path is None:
        return 0, {}
    frame = pd.read_csv(path)
    if "reason" not in frame.columns:
        raise ValueError("Rejected-candidate file must contain a reason column")
    counts = {str(key): int(value) for key, value in frame["reason"].value_counts().items()}
    return int(len(frame)), counts


def run_replay(
    trades_path: str | Path,
    rejected_path: str | Path | None = None,
    initial_balance: float = DEFAULT_RULES.initial_balance,
) -> ReplayResult:
    frame = load_synchronized_trades(trades_path)
    realized_curve, stress_curve = build_equity_curves(frame, initial_balance)
    realized_dd = _maximum_drawdown_percent(realized_curve)
    stress_dd = _maximum_drawdown_percent(stress_curve)

    portfolio = _performance(frame, initial_balance, realized_dd)
    summaries: list[dict[str, Any]] = []
    for engine, group in frame.groupby("engine", sort=True):
        # Per-engine DD is reported on an isolated initial balance. Portfolio DD
        # remains the authoritative synchronized risk statistic.
        isolated = [initial_balance]
        balance = initial_balance
        for pnl in group.sort_values("exit_time")["pnl"]:
            balance += float(pnl)
            isolated.append(balance)
        summaries.append({
            "engine": str(engine),
            **asdict(_performance(
                group,
                initial_balance,
                _maximum_drawdown_percent(isolated),
            )),
        })

    rejected, reasons = load_rejections(rejected_path)
    return ReplayResult(
        initial_balance=float(initial_balance),
        ending_balance=float(initial_balance + frame["pnl"].sum()),
        realized_drawdown_percent=realized_dd,
        open_risk_stress_drawdown_percent=stress_dd,
        portfolio=portfolio,
        engine_summary=summaries,
        rejected_candidates=rejected,
        rejection_reasons=reasons,
        methodology=(
            "Synchronized trade-ledger replay using exact reserved risk and R outcomes; "
            "stress equity marks every open position at its full reserved loss."
        ),
    )


def _json_default(value: Any) -> Any:
    if value == float("inf"):
        return "Infinity"
    raise TypeError(f"Object of type {type(value).__name__} is not JSON serializable")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Verify Strategy Engine V8 synchronized results")
    parser.add_argument("trades", help="Accepted synchronized-trades CSV")
    parser.add_argument("--rejected", help="Rejected-candidates CSV")
    parser.add_argument("--balance", type=float, default=DEFAULT_RULES.initial_balance)
    parser.add_argument("--output", help="Optional JSON output path")
    args = parser.parse_args(argv)

    result = run_replay(args.trades, args.rejected, args.balance)
    payload = json.dumps(result.to_dict(), indent=2, default=_json_default)
    print(payload)
    if args.output:
        output = Path(args.output)
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(payload + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
